logging:
  level:
    ROOT: INFO
    org.springframework: INFO

spring:
  application:
    name: console-packages
  shell:
    interactive:
      enabled: true

telegram:
  bot:
    enabled: true
    username: "AppBoxInTruckBot"
    token: "7759796407:AAEYrYl1NHtCGcx7OMr7KhI5hIXH40Gfsk0"

billing:
  cost-load: 50
  cost-unload: 80
