server:
  port: 8081

logging:
  level:
    ROOT: INFO
    org.springframework: INFO

swagger:
  url:
    path: /

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    path: ${swagger.url.path}swagger/v3/api-docs

spring:
  application:
    name: logistic-billing
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5433/logistic_billing_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9094
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${bootstrap-servers}
        bindings:
          billing-in-0:
            consumer:
              start-offset: earliest
      bindings:
        billing-in-0:
          destination: billing.orders.v0
          contentType: application/json
          group: billing_service_group
          consumer:
            max-attempts: 5
            concurrency: 1

billing:
  cost-load: 50
  cost-unload: 80

