server:
  port: 8080

logging:
  level:
    ROOT: INFO
    org.springframework: INFO

swagger:
  url:
    path: /

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    path: ${swagger.url.path}swagger/v3/api-docs

spring:
  application:
    name: logistic-service
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/logistic_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9094
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${bootstrap-servers}
          auto-create-topics: true
          auto-add-partitions: true
      bindings:
        billing-out-0:
          destination: billing.orders.v0
          contentType: application/json
          producer:
            partition-count: 1