server:
  port: 8081

spring:
  application:
    name: logistic-cli
  shell:
    interactive:
      enabled: true

services:
  logistic-service-url: "http://localhost:8080"
  logistic-billing-url: "http://localhost:8081"