CREATE TABLE "order"
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type          VARCHAR(255)                            NOT NULL,
    client_name   VARCHAR(255),
    date          date,
    truck_count   BIGINT,
    box_count     BIGINT,
    segment_count BIGINT,
    amount        DECIMAL,
    CONSTRAINT pk_order PRIMARY KEY (id)
);

CREATE TABLE order_inbox
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date   TIMESTAMP WITHOUT TIME ZONE,
    order_id       BIGINT,
    idempotent_key UUID,
    CONSTRAINT pk_order_inbox PRIMARY KEY (id)
);

ALTER TABLE order_inbox
    ADD CONSTRAINT uc_order_inbox_idempotentkey UNIQUE (idempotent_key);

ALTER TABLE order_inbox
    ADD CONSTRAINT uc_order_inbox_order UNIQUE (order_id);

ALTER TABLE order_inbox
    ADD CONSTRAINT fk_order_inbox_on_order FOREIGN KEY (order_id) REFERENCES "order" (id);