CREATE TABLE box
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR(255),
    form   VARCHAR(255),
    symbol VARCHAR(255),
    CONSTRAINT pk_box PRIMARY KEY (id)
);

CREATE TABLE "order"
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type          VARCHAR(255)                            NOT NULL,
    client_name   VARCHAR(255),
    date          date,
    truck_count   BIGINT,
    box_count     BIGINT,
    segment_count BIGINT,
    CONSTRAINT pk_order PRIMARY KEY (id)
);

CREATE TABLE order_outbox
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date   TIMESTAMP WITHOUT TIME ZONE,
    order_id       BIGINT,
    idempotent_key UUID,
    status         VARCHAR(255),
    CONSTRAINT pk_order_outbox PRIMARY KEY (id)
);

ALTER TABLE order_outbox
    ADD CONSTRAINT uc_order_outbox_idempotentkey UNIQUE (idempotent_key);

ALTER TABLE order_outbox
    ADD CONSTRAINT uc_order_outbox_order UNIQUE (order_id);

ALTER TABLE order_outbox
    ADD CONSTRAINT fk_order_outbox_on_order FOREIGN KEY (order_id) REFERENCES "order" (id);