CREATE TABLE "order"
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type          VARCHAR(255)                            NOT NULL,
    client_name   VARCHAR(255),
    date          date,
    truck_count   BIGINT,
    box_count     BIGINT,
    segment_count BIGINT,
    CONSTRAINT pk_order PRIMARY KEY (id)
);